
export const FACILITY_GET_REQUEST = 'FACILITY_GET_REQUEST'
export const FACILITY_GET_SUCCESS = 'FACILITY_GET_SUCCESS'
export const FACILITY_GET_FAIL = 'FACILITY_GET_FAIL'

export const FACILITY_LIST_REQUEST = 'FACILITY_LIST_REQUEST';
export const FACILITY_LIST_SUCCESS = 'FACILITY_LIST_SUCCESS';
export const FACILITY_LIST_FAIL = 'FACILITY_LIST_FAIL';

export const FACILITY_ACTIVE_REQUEST = 'FACILITY_ACTIVE_REQUEST';
export const FACILITY_ACTIVE_SUCCESS = 'FACILITY_ACTIVE_SUCCESS';
export const FACILITY_ACTIVE_FAIL = 'FACILITY_ACTIVE_FAIL';

export const FACILITY_RECOVERED_REQUEST = 'FACILITY_RECOVERED_REQUEST';
export const FACILITY_RECOVERED_SUCCESS = 'FACILITY_RECOVERED_SUCCESS';
export const FACILITY_RECOVERED_FAIL = 'FACILITY_RECOVERED_FAIL';

export const FACILITY_DEATHS_REQUEST = 'FACILITY_DEATHS_REQUEST';
export const FACILITY_DEATHS_SUCCESS = 'FACILITY_DEATHS_SUCCESS';
export const FACILITY_DEATHS_FAIL = 'FACILITY_DEATHS_FAIL';

export const FACILITY_BEDS_REQUEST = 'FACILITY_BEDS_REQUEST';
export const FACILITY_BEDS_SUCCESS = 'FACILITY_BEDS_SUCCESS';
export const FACILITY_BEDS_FAIL = 'FACILITY_BEDS_FAIL';
