export const PATIENT_LIST_REQUEST = 'PATIENT_LIST_REQUEST'
export const PATIENT_LIST_SUCCESS = 'PATIENT_LIST_SUCCESS'
export const PATIENT_LIST_FAIL = 'PATIENT_LIST_FAIL'

export const PATIENT_DETAILS_REQUEST = 'PATIENT_DETAILS_REQUEST'
export const PATIENT_DETAILS_SUCCESS = 'PATIENT_DETAILS_SUCCESS'
export const PATIENT_DETAILS_FAIL = 'PATIENT_DETAILS_FAIL'

export const PATIENT_UPDATE_REQUEST = 'PATIENT_UPDATE_REQUEST'
export const PATIENT_UPDATE_SUCCESS = 'PATIENT_UPDATE_SUCCESS'
export const PATIENT_UPDATE_FAIL = 'PATIENT_UPDATE_FAIL'
export const PATIENT_UPDATE_RESET = 'PATIENT_UPDATE_RESET'

export const PATIENT_REPORT_REQUEST = 'PATIENT_REPORT_REQUEST'
export const PATIENT_REPORT_SUCCESS = 'PATIENT_REPORT_SUCCESS'
export const PATIENT_REPORT_FAIL = 'PATIENT_REPORT_FAIL'

export const REPORT_UPDATE_REQUEST = 'REPORT_UPDATE_REQUEST'
export const REPORT_UPDATE_SUCCESS = 'REPORT_UPDATE_SUCCESS'
export const REPORT_UPDATE_FAIL = 'REPORT_UPDATE_FAIL'
export const REPORT_UPDATE_RESET = 'REPORT_UPDATE_RESET'