export const PATIENT_ADMIT_REQUEST = 'PATIENT_ADMIT_REQUEST'
export const PATIENT_ADMIT_SUCCESS = 'PATIENT_ADMIT_SUCCESS'
export const PATIENT_ADMIT_FAIL = 'PATIENT_ADMIT_FAIL'

export const PATIENT_DISCHARGE_REQUEST = 'PATIENT_DISCHARGE_REQUEST'
export const PATIENT_DISCHARGE_SUCCESS = 'PATIENT_DISCHARGE_SUCCESS'
export const PATIENT_DISCHARGE_FAIL = 'PATIENT_DISCHARGE_FAIL'


export const PATIENT_TRANSFER_REQUEST = 'PATIENT_TRANSFER_REQUEST'
export const PATIENT_TRANSFER_SUCCESS = 'PATIENT_TRANSFER_SUCCESS'
export const PATIENT_TRANSFER_FAIL = 'PATIENT_TRANSFER_FAIL'

export const PATIENT_LIST_REQUEST = 'PATIENT_LIST_REQUEST'
export const PATIENT_LIST_SUCCESS = 'PATIENT_LIST_SUCCESS'
export const PATIENT_LIST_FAIL = 'PATIENT_LIST_FAIL'

export const PATIENT_DETAILS_REQUEST = 'PATIENT_DETAILS_REQUEST'
export const PATIENT_DETAILS_SUCCESS = 'PATIENT_DETAILS_SUCCESS'
export const PATIENT_DETAILS_FAIL = 'PATIENT_DETAILS_FAIL'

export const PATIENT_UPDATE_REQUEST = 'PATIENT_UPDATE_REQUEST'
export const PATIENT_UPDATE_SUCCESS = 'PATIENT_UPDATE_SUCCESS'
export const PATIENT_UPDATE_FAIL = 'PATIENT_UPDATE_FAIL'
export const PATIENT_UPDATE_RESET = 'PATIENT_UPDATE_RESET'