export const PATIENT_ADMIT_REQUEST = 'PATIENT_ADMIT_REQUEST'
export const PATIENT_ADMIT_SUCCESS = 'PATIENT_ADMIT_SUCCESS'
export const PATIENT_ADMIT_FAIL = 'PATIENT_ADMIT_FAIL'

export const PATIENT_DISCHARGE_REQUEST = 'PATIENT_DISCHARGE_REQUEST'
export const PATIENT_DISCHARGE_SUCCESS = 'PATIENT_DISCHARGE_SUCCESS'
export const PATIENT_DISCHARGE_FAIL = 'PATIENT_DISCHARGE_FAIL'


export const PATIENT_TRANSFER_REQUEST = 'PATIENT_TRANSFER_REQUEST'
export const PATIENT_TRANSFER_SUCCESS = 'PATIENT_TRANSFER_SUCCESS'
export const PATIENT_TRANSFER_FAIL = 'PATIENT_TRANSFER_FAIL'