
export const REPORT_CREATE_REQUEST = 'TEST_ENTER_REQUEST'
export const REPORT_CREATE_SUCCESS = 'TEST_ENTER_SUCCESS'
export const REPORT_CREATE_FAIL = 'TEST_ENTER_FAIL'

export const PATIENT_REPORT_REQUEST = 'PATIENT_REPORT_REQUEST'
export const PATIENT_REPORT_SUCCESS = 'PATIENT_REPORT_SUCCESS'
export const PATIENT_REPORT_FAIL = 'PATIENT_REPORT_FAIL'

export const REPORT_UPDATE_REQUEST = 'REPORT_UPDATE_REQUEST'
export const REPORT_UPDATE_SUCCESS = 'REPORT_UPDATE_SUCCESS'
export const REPORT_UPDATE_FAIL = 'REPORT_UPDATE_FAIL'
export const REPORT_UPDATE_RESET = 'REPORT_UPDATE_RESET'


