export const TEST_ENTER_REQUEST = 'TEST_ENTER_REQUEST'
export const TEST_ENTER_SUCCESS = 'TEST_ENTER_SUCCESS'
export const TEST_ENTER_FAIL = 'TEST_ENTER_FAIL'

export const TEST_DETAILS_REQUEST = 'TEST_DETAILS_REQUEST'
export const TEST_DETAILS_SUCCESS = 'TEST_DETAILS_SUCCESS'
export const TEST_DETAILS_FAIL = 'TEST_DETAILS_FAIL'
